# This is a basic workflow to help you get started with Actions

name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
   name: Build
   strategy:
        matrix:
          python-version: [3.9.x,3.10.x]
          platform: [windows-latest]
   runs-on: ${{matrix.platform}}
   steps:
   - name: Set up Python ${{matrix.node-version}}
     uses: actions/setup-python@v2
     with:
       python-version: ${{matrix.python-version}}
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Test
     run: python test_money.py -v
     shell: bash
